---
# tasks file for ansible-role-dsu

- name: Make sure this is only run on a dell server
  assert:
    that: ansible_system_vendor is match('Dell.*')
    msg: "This role is only meant to be run on Dell systems"
  when: dsu_assert

- name: get DSU repo from dell
  ansible.builtin.get_url:
    url: "{{ dsu_url }}"
    dest: "{{ dsu_bootstrap_local_copy }}"
    force: yes

- name: modify Dell bootstrap file
  ansible.builtin.lineinfile:
    backrefs: true
    path: "{{ dsu_bootstrap_local_copy }}"
    regexp: '^IMPORT_GPG_CONFIRMATION="na"$'
    line: 'IMPORT_GPG_CONFIRMATION="yes"'
  notify:
    - update dsu repo and keys
    - install the latest dell-system-update

- name: clean up dsu bootstrap file
  ansible.builtin.file:
    path: "{{ dsu_bootstrap_local_copy }}"
    state: absent
  when: dsu_cleanup
