---
# tasks file for ansible-role-dsu

- name: Make sure this is only run on a dell server
  assert:
    that: ansible_system_vendor is match('Dell.*')
    msg: "This role is only meant to be run on Dell systems"
  when: dsu_assert

- name: get DSU repo from dell
  ansible.builtin.get_url:
    url: "{{ dsu_url }}"
    dest: "{{ dsu_bootstrap_local_copy }}"
    force: yes

- name: modify Dell bootstrap file
  ansible.builtin.lineinfile:
    backrefs: true
    path: "{{ dsu_bootstrap_local_copy }}"
    regexp: '^IMPORT_GPG_CONFIRMATION="na"$'
    line: 'IMPORT_GPG_CONFIRMATION="yes"'

- name: update dsu repo and keys
  ansible.builtin.command: bash "{{ dsu_bootstrap_local_copy }}"

  # This sometimes fails due to mirrorlist CGI problem
  # E.g. always when setting release as "9.6" instead of "9"
- name: install the latest dell-system-update
  ansible.builtin.dnf:
    name: dell-system-update
    state: latest
    update_cache: true
  register: result
  ignore_errors: yes

- block:
  - name: Replace mirrorlist line in dell-system-update.repo
    ansible.builtin.lineinfile:
      path: /etc/yum.repos.d/dell-system-update.repo
      regexp: '^mirrorlist='
      line: 'baseurl=https://linux.dell.com/repo/hardware/dsu/os_dependent/RHEL9_64/'

  - name: install the latest dell-system-update
    ansible.builtin.dnf:
      name: dell-system-update
      state: latest
      update_cache: true

 # when: result.rc != 0
  when: rhel_release is defined

- name: clean up dsu bootstrap file
  ansible.builtin.file:
    path: "{{ dsu_bootstrap_local_copy }}"
    state: absent
  when: dsu_cleanup
