---
# handlers file for ansible-role-dsu

- name: update dsu repo and keys
  ansible.builtin.command: /bin/bash /root/bootstrap.cgi

- name: install the latest dell-system-update
  ansible.builtin.dnf:
    name: dell-system-update
    state: latest
    update_cache: true
